NAME = libft.a
CC = cc
CFLAGS = -Wall -Wextra -Werror -g3

###########################Sources#############################
SRCS = \
	ft_atoi.c ft_bzero.c ft_calloc.c ft_isalnum.c \
	ft_isalpha.c ft_isascii.c ft_isdigit.c ft_isprint.c \
	ft_itoa.c ft_memchr.c ft_memcmp.c ft_memcpy.c \
	ft_memmove.c ft_memset.c ft_putchar_fd.c \
	ft_putendl_fd.c ft_putnbr_fd.c ft_putstr_fd.c \
	ft_split.c ft_strchr.c ft_strdup.c ft_striteri.c \
	ft_strjoin.c ft_strlcat.c ft_strlcpy.c ft_strlen.c \
	ft_strmapi.c ft_strncmp.c ft_strnstr.c ft_strrchr.c \
	ft_strtrim.c ft_substr.c ft_tolower.c ft_toupper.c \
	ft_lstadd_back.c ft_lstadd_front.c \
	ft_lstclear.c ft_lstdelone.c ft_lstmap.c \
	ft_lstnew.c ft_lstsize.c ft_lstiter.c \
	ft_lstlast.c ft_strlen_to_c.c ft_strcpy.c ft_strcmp.c

###########################Objects#############################
OBJS = ${SRCS:.c=.o}

%.o:%.c
	${CC} ${CFLAGS} -c $< -o ${<:.c=.o}

all: ${NAME}

${NAME}: ${OBJS}
	@${MAKE} -C ./ft_printf
	@${MAKE} -C ./get_next_line
	@${MAKE} -C ./gnl_no_malloc
	ar rcs ${NAME} ${OBJS} ./ft_printf/libftprintf.a ./get_next_line/libgnl.a $?

clean:
	@${MAKE} -C ./ft_printf fclean
	@${MAKE} -C ./get_next_line fclean
	@${MAKE} -C ./gnl_no_malloc fclean
	rm -f ${OBJS}

fclean: clean
	rm -f ${NAME}

re: fclean all

.PHONY: all clean fclean re bonus
